### ISSUE TITLE
could not find function "FOCuS_offline"

### ISSUE THREAD

**Issue by raphael-fua** [gtromano/FOCuS#9]
When running cost_function_illustration.R, I get the following error

Error in FOCuS_offline(y = y[1:(start + i)], mu0 = 0, thres = Inf) : 
  could not find function "FOCuS_offline"

**Comment by gtromano** [comment]
Dear Raphael, 

this bug was caused by a previous interface (now deprecated) to FOCuS. Hopefully the issue should be fixed now.
